apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-cloud-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multi-cloud-backend
  template:
    metadata:
      labels:
        app: multi-cloud-backend
    spec:
      containers:
      - name: multi-cloud-backend
        image: <your-docker-image>
        ports:
        - containerPort: 3000
      resources:
        limits:
          memory: "512Mi"
          cpu: "500m"
        requests:
          memory: "256Mi"
          cpu: "250m"
